Setup cleans first
`make setup` runs `make clean` first because running `make setup` an n+1 time will fail with:

  OSError: [Errno 62] Too many levels of symbolic links

And tells the user how to activate the environment.